M48
; DRILL file {KiCad (6.0.6)} date Mon Oct 17 14:20:43 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-17T14:20:43+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0512
%
G90
G05
T1
X3.3Y-2.3
X3.3Y-2.4
X3.3Y-2.5
X3.3Y-2.6
X4.0Y-2.3
X4.0Y-2.4
X4.0Y-2.5
X4.0Y-2.6
T0
M30
